using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ProductCatalog.Domain.Entities;

namespace ProductCatalog.Infrastructure.Persistence.Configurations;

public class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.ToTable("Products");

        builder.HasKey(p => p.Id);

        // The 6-digit ID is generated by the application (see IProductIdGenerator), never by the
        // database — the PK's own uniqueness constraint is what ultimately rejects a collision
        // from a concurrently-running instance.
        builder.Property(p => p.Id).ValueGeneratedNever();

        builder.Property(p => p.Name).IsRequired().HasMaxLength(200);
        builder.Property(p => p.Description).HasMaxLength(1000);
        builder.Property(p => p.Price).HasColumnType("decimal(18,2)");
        builder.Property(p => p.StockQuantity).IsRequired();

        // Optimistic concurrency token protecting concurrent stock updates.
        builder.Property(p => p.RowVersion).IsRowVersion();

        builder.HasIndex(p => p.Name);
    }
}
